Feat[TEO-778] - View NGO Profile
code4romania/teo pull request #143
Opened 2023-05-02 14:10 UTC by biggicode

[[TEO-778]](https://wearetribus.atlassian.net/browse/TEO-778)

2023-05-17 09:06 UTC, birloiflorian requested changes

2023-05-17 09:06 UTC, birloiflorian commented on mobile/src/assets/svg/clock.js
Please use the icon from feather

2023-05-17 09:06 UTC, birloiflorian commented on mobile/src/components/EventPresenter.tsx
> +    <TouchableHighlight onPress={onPress} underlayColor="#F9F9F9">
Please use the underlayColor from theme.

2023-05-17 09:06 UTC, birloiflorian commented on mobile/src/components/EventPresenter.tsx
> +const EventPresenter = ({ title, date, location, divison, onPress }: EventPresenterProps) => {
This should be the EventItem

2023-05-17 09:06 UTC, birloiflorian commented on mobile/src/components/IconSvg.tsx
> +const IconSvg = ({ icon, size, fill = '#9CA3AF', ...svgProps }: IconSvgProps) => (
Same here please use the fill color from the theme

2023-05-17 09:06 UTC, birloiflorian commented on mobile/src/components/Statistics.tsx
> -          icon={<IconSvg icon={ClockSvg} size={56} />}
Fill color from themeing

2023-05-17 09:06 UTC, birloiflorian commented on mobile/src/screens/OrganizationProfile.tsx
> +      <ScrollView>
Use the ScrollViewLayout component here

2023-05-18 08:36 UTC, biggicode commented on mobile/src/screens/OrganizationProfile.tsx
> +      <ScrollView>
This needs discussion

2023-05-19 07:21 UTC, birloiflorian approved these changes

2023-05-19 07:21 UTC, birloiflorian commented on mobile/src/screens/OrganizationProfile.tsx
> +      <ScrollView>
we leave it like this for now

2023-05-19 07:21 UTC, merged