Feature[TEO-141] OrganizationProfile component
code4romania/teo pull request #17
Opened 2023-02-03 14:28 UTC by biggicode

https://wearetribus.atlassian.net/browse/TEO-141

2023-02-03 15:49 UTC, birloiflorian requested changes

2023-02-03 15:49 UTC, birloiflorian commented on frontend/src/assets/locales/ro/translation.json
> +  "organization_profile": {
this should be called "organization", not necessary to be called "organization_profile".

2023-02-03 15:49 UTC, birloiflorian commented on frontend/src/assets/locales/ro/translation.json
> +    "button_label": "Editează",
This should be in "general". Please align with this PR: https://github.com/code4romania/teo/pull/15/files

2023-02-03 15:49 UTC, birloiflorian commented on frontend/src/assets/locales/ro/translation.json
> +    "data_info": "Datele sunt preluate din ONGHub.",
This is "subtitle"

2023-02-03 15:49 UTC, birloiflorian commented on frontend/src/assets/locales/ro/translation.json
> +    "email": "Email",
email, phone, address are generic namings not specific to the organization and should be present in "general", please refer to the PR above.

2023-02-03 15:49 UTC, birloiflorian commented on frontend/src/components/OrganizationProfile.tsx
> +              src="logo.svg"
this should come from the organization.

2023-02-06 13:29 UTC, birloiflorian requested changes

2023-02-06 13:29 UTC, birloiflorian commented on frontend/src/components/OrganizationProfile.tsx
> +          label={t('edit')}
Does this translation work?

2023-02-06 13:29 UTC, birloiflorian commented on frontend/src/components/OrganizationProfile.tsx
> +        <h2>{t('title')}</h2>
Please validate with @OlteanuCosmin and @AndreeaMariaP for the font behaviour on mobile devices.

2023-02-08 11:47 UTC, birloiflorian commented on frontend/src/assets/locales/ro/translation.json
> +    "organization_naming": "Denumire organizație",
This is not resolved.

2023-02-08 12:56 UTC, birloiflorian commented on frontend/src/components/OrganizationProfile.tsx
> +              src={organization.logo}
We need to handle scenario if logo is not provided. Maybe we should have a placeholder.

2023-02-08 15:40 UTC, biggicode commented on frontend/src/components/OrganizationProfile.tsx
> +          onClick={() => navigate('edit')}
Done

2023-02-08 15:41 UTC, biggicode commented on frontend/src/pages/Organization.tsx
> +  const { data: organization, error: organizationProfileError } = useOrganizationProfileQuery();
Done

2023-02-08 16:09 UTC, merged