feat: [TEO-118] add/edit BDR
code4romania/teo pull request #27
Opened 2023-02-09 12:44 UTC by OlteanuCosmin

[TEO-118](https://wearetribus.atlassian.net/browse/TEO-118)

2023-02-09 15:28 UTC, radulescuandrew requested changes

2023-02-09 15:28 UTC, radulescuandrew commented on frontend/src/assets/locales/ro/translation.json
> +      "custom": {
Scoatem layer de "custom". Nu e nevoie sa le mai bagam inca intr-un obiect

2023-02-09 15:28 UTC, radulescuandrew commented on frontend/src/assets/locales/ro/translation.json
> +      "generic": {
Nici aici n-avem nevoie de layer

2023-02-09 15:28 UTC, radulescuandrew commented on frontend/src/services/division/division.service.ts
> +    onError: (error: AxiosError<IBusinessException<DISVISION_ERRORS>>) => Promise.resolve(error),
`DISVISION` typo

2023-02-09 15:54 UTC, birloiflorian commented on frontend/src/components/Divisions.tsx
> +  const { mutateAsync: addDivisionMutation } = useAddDivisionMutation();
We need to handle loading state, while the request is done the table should be showing the loading icon.

2023-02-09 15:55 UTC, birloiflorian commented on frontend/src/components/Divisions.tsx
> +          i18n.t('division:errors.generic.add', {
Please use the generic error class

2023-02-09 15:56 UTC, birloiflorian commented on frontend/src/components/Divisions.tsx
> +            if (editDivisionMutationError)
this error comes on onError callback, we don't need to get it from the hook, since we use the callback we should get it from there.

2023-02-09 15:56 UTC, birloiflorian commented on frontend/src/services/division/division.service.ts
> +    onError: (error: AxiosError<IBusinessException<DISVISION_ERRORS>>) => Promise.resolve(error),
:)) This is me

2023-02-10 12:44 UTC, birloiflorian approved these changes

2023-02-10 12:44 UTC, merged